# Generated by Django 2.2.28 on 2023-03-12 17:04

from django.db import migrations
import inyoka.utils.database


class Migration(migrations.Migration):

    dependencies = [
        ('ikhaya', '0009_auto_20191027_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='intro',
            field=inyoka.utils.database.InyokaMarkupField(application='ikhaya', force_existing=False, simplify=False, verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=inyoka.utils.database.InyokaMarkupField(application='ikhaya', force_existing=False, simplify=False, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=inyoka.utils.database.InyokaMarkupField(application='ikhaya', force_existing=False, simplify=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='text',
            field=inyoka.utils.database.InyokaMarkupField(application='ikhaya', force_existing=False, simplify=False),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='intro',
            field=inyoka.utils.database.InyokaMarkupField(application='ikhaya', force_existing=False, simplify=False, verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='notes',
            field=inyoka.utils.database.InyokaMarkupField(application='ikhaya', blank=True, default='', force_existing=False, simplify=False, verbose_name='Annotations to the team'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='text',
            field=inyoka.utils.database.InyokaMarkupField(application='ikhaya', force_existing=False, simplify=False, verbose_name='Text'),
        ),
    ]
