# Generated by Django 4.2.13 on 2024-06-15 22:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ikhaya", "0010_auto_20230312_1704"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestion",
            name="pub_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Datum"
            ),
        ),
    ]
