# Generated by Django 4.2.18 on 2025-02-22 23:37
import datetime

from django.db import migrations


def adjust_comment_datetime(apps, schema_editor):
    comment_model = apps.get_model("ikhaya", "Comment")

    for c in comment_model.objects.all():
        c.pub_date = c.pub_date.astimezone().replace(tzinfo=datetime.timezone.utc)
        c.save(update_fields=["pub_date"])

class Migration(migrations.Migration):

    dependencies = [
        ("ikhaya", "0011_article_publication_datetime"),
    ]

    operations = [
        migrations.RunPython(
            code=adjust_comment_datetime,
        ),
    ]
