# Generated by Django 4.2.17 on 2024-12-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ikhaya", "0011_alter_suggestion_pub_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="article",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="article",
            name="updated",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="If you keep this field empty, the publication date will be used.",
                null=True,
                verbose_name="Last change",
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.UniqueConstraint(
                models.F("pub_date"), models.F("slug"), name="unique_pub_date_slug"
            ),
        ),
    ]
