# Generated by Django 4.2.17 on 2024-12-26 17:03
import datetime

import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


def populate_publication_datetime(apps, schema_editor):
    article_model = apps.get_model("ikhaya", "Article")

    for a in article_model.objects.all():
        p_datetime = datetime.datetime.combine(a.pub_date, a.pub_time, datetime.timezone.utc)
        a.publication_datetime = p_datetime
        a.save()


class Migration(migrations.Migration):

    dependencies = [
        ("ikhaya", "0012_alter_article__unique_constraint__updated_verbose_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="article",
            name="unique_pub_date_slug",
        ),
        migrations.AddField(
            model_name="article",
            name="publication_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Publication time"
            ),
        ),
        migrations.RunPython(populate_publication_datetime),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.UniqueConstraint(
                django.db.models.functions.datetime.TruncDate("publication_datetime"),
                models.F("slug"),
                name="unique_pub_date_slug",
            ),
        ),
    ]
