# Generated by Django 4.2.17 on 2024-12-27 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ikhaya", "0013_move_to_publication_datetime"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-publication_datetime", "author"],
                "permissions": (
                    ("view_unpublished_article", "Can view unpublished articles"),
                    ("suggest_article", "Can suggest articles"),
                ),
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
        migrations.RemoveField(
            model_name="article",
            name="pub_date",
        ),
        migrations.RemoveField(
            model_name="article",
            name="pub_time",
        ),
    ]
