# Generated by Django 4.2.17 on 2025-01-03 15:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ikhaya", "0014_alter_article_options_remove_article_pub_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestion",
            name="pub_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date"
            ),
        ),
    ]
