# Generated by Django 4.2.17 on 2025-01-03 17:05

from django.db import migrations
from django.db.models import F


def set_updated_to_none_where_it_equals_publication(apps, schema_editor):
    """
    Set `Article.updated` to the value None (python) / NULL (SQL) where `updated` has the
    same value as `publication_datetime`.
    """
    article_model = apps.get_model("ikhaya", "Article")

    article_model.objects.filter(updated=F('publication_datetime')).update(updated=None)


class Migration(migrations.Migration):

    dependencies = [
        ("ikhaya", "0015_alter_suggestion_pub_date"),
    ]

    operations = [
        migrations.RunPython(set_updated_to_none_where_it_equals_publication),
    ]
