# Generated by Django 4.2.17 on 2025-01-05 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ikhaya", "0017_article_unique_constraint_pub_date_slug_in_utc"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "permissions": (
                    ("view_unpublished_article", "Can view unpublished articles"),
                    ("suggest_article", "Can suggest articles"),
                ),
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
    ]
