# Generated by Django 1.11.25 on 2019-10-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_remove_text_html_render_instructions_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='wiki/attachments/%S/%W'),
        ),
    ]
