# Generated by Django 3.2.23 on 2024-02-05 23:56

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_auto_20230312_1704'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='page',
            index=models.Index(django.db.models.functions.text.Upper('name'), name='upper_page_name_idx'),
        ),
    ]
