# Generated by Django 4.2.18 on 2025-02-23
import datetime

from django.db import migrations


def adjust_revision_datetime(apps, schema_editor):
    revision_model = apps.get_model("wiki", "Revision")

    for r in revision_model.objects.all():
        r.change_date = r.change_date.astimezone().replace(tzinfo=datetime.timezone.utc)
        r.save(update_fields=["change_date"])


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0006_page_upper_page_name_idx"),
    ]

    operations = [
        migrations.RunPython(
            code=adjust_revision_datetime,
        ),
    ]
