# Generated by Django 5.2 on 2025-05-05
from hashlib import sha1

from django.conf import settings
from django.db import migrations
from django.utils import timezone as dj_timezone


def create_wiki_index(apps, schema_editor):
    user_model = apps.get_model("portal", "User")
    page_model = apps.get_model("wiki", "Page")

    index_page_name = 'Wiki/Index'
    indexes = page_model.objects.filter(name__iexact=index_page_name).exists()

    if not indexes:
        system_user = user_model.objects.get(username__iexact=settings.INYOKA_SYSTEM_USER)

        revision_model = apps.get_model('wiki', 'Revision')
        text_model = apps.get_model('wiki', 'Text')
        p = page_model(
            name=index_page_name,
        )
        p.save()

        value = '[[PageList()]]'
        text = text_model.objects.create(value=value, hash=sha1(value.encode('utf-8')).hexdigest())

        p.rev = revision_model(
            page=p,
            text=text,
            user=system_user,
            change_date=dj_timezone.now(),
            note='Automatically created index',
        )
        p.rev.save()
        p.last_rev = p.rev
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0007_adjust_datetimes"),
    ]

    operations = [
        migrations.RunPython(
            code=create_wiki_index,
        ),
    ]
