# Generated by Django 1.11.13 on 2019-04-15 00:16


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_django_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(max_length=250, upload_to='forum/attachments/temp'),
        ),
    ]
