# Generated by Django 2.1.15 on 2021-01-08 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_auto_20191027_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum',
            options={'permissions': (('delete_topic_forum', 'Can delete Topics from Forum'), ('add_topic_forum', 'Can add Topic in Forum'), ('add_reply_forum', 'Can answer Topics in Forum'), ('sticky_forum', 'Can make Topics Sticky in Forum'), ('poll_forum', 'Can make Polls in Forum'), ('vote_forum', 'Can make Votes in Forum'), ('upload_forum', 'Can upload Attachments in Forum'), ('moderate_forum', 'Can moderate Forum')), 'verbose_name': 'Forum', 'verbose_name_plural': 'Forums'},
        ),
    ]
