# Generated by Django 2.2.28 on 2023-03-12 17:04

from django.db import migrations
import inyoka.utils.database


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_auto_20210108_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='welcome_text',
            field=inyoka.utils.database.InyokaMarkupField(application='forum', blank=True, force_existing=False, null=True, simplify=False, verbose_name='Welcome text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=inyoka.utils.database.InyokaMarkupField(application='forum', force_existing=False, simplify=False),
        ),
        migrations.AlterField(
            model_name='postrevision',
            name='text',
            field=inyoka.utils.database.InyokaMarkupField(application='forum', force_existing=False, simplify=False),
        ),
    ]
