# Generated by Django 4.2.13 on 2024-06-15 22:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0016_auto_20230312_1704"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="post",
            name="pub_date",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="postrevision",
            name="store_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
