# Generated by Django 4.2.18 on 2025-02-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0017_alter_poll_start_time_alter_post_pub_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="slug",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
