# Generated by Django 4.2.18 on 2025-02-22 16:08
import datetime

from django.db import migrations


def adjust_post_datetime(apps, schema_editor):
    post_model = apps.get_model("forum", "Post")

    for p in post_model.objects.all():
        p.pub_date = p.pub_date.astimezone().replace(tzinfo=datetime.timezone.utc)
        p.save(update_fields=["pub_date"])


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0018_add_index__topic_slug"),
    ]

    operations = [
        migrations.RunPython(
            code=adjust_post_datetime,
        ),
    ]
