# Generated by Django 5.2.14 on 2026-05-06 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0019_adjust_datetimes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="forum",
            options={
                "permissions": (
                    ("delete_topic_forum", "Can delete Topics from Forum"),
                    ("add_topic_forum", "Can add Topic in Forum"),
                    ("add_reply_forum", "Can answer Topics in Forum"),
                    ("sticky_forum", "Can make Topics Sticky in Forum"),
                    ("poll_forum", "Can make Polls in Forum"),
                    ("vote_forum", "Can make Votes in Forum"),
                    ("upload_forum", "Can upload Attachments in Forum"),
                    ("moderate_forum", "Can moderate Forum"),
                    ("manage_tickets_forum", "Can manage tickets for Forums"),
                ),
                "verbose_name": "Forum",
                "verbose_name_plural": "Forums",
            },
        ),
    ]
