# Generated by Django 5.2.17 on 2026-09-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0020_add_manage_tickets_permission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={"verbose_name": "Topic", "verbose_name_plural": "Topics"},
        ),
    ]
