# Generated by Django 5.2.17 on 2026-09-20 18:50

from django.db import migrations


def rm_perm_manage_reported_topic(apps, schema_editor):
    """
    remove old db entries for permission `forum.manage_reported_topic`
    """

    permission_model = apps.get_model('auth', 'Permission')
    permission_model.objects.filter(
        codename='manage_reported_topic',
        content_type__app_label='forum',
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('forum', '0021_alter_topic_options'),
    ]

    operations = [
        migrations.RunPython(
            code=rm_perm_manage_reported_topic,
        ),
    ]
