# Generated by Django 5.2.17 on 2026-09-25 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0022_rm_perm_manage_reported_topic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="report_claimed_by",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="reported",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="reporter",
        ),
    ]
