# Generated by Django 1.11.25 on 2019-10-27 18:14

from django.db import migrations
import inyoka.utils.database


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0005_remove_entry_referrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='code',
            field=inyoka.utils.database.PygmentsField(application='pastebin'),
        ),
    ]
