# Generated by Django 2.1.15 on 2021-01-08 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0006_auto_20191027_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('-id',), 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
    ]
