# Generated by Django 4.2.13 on 2024-06-15 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pastebin", "0007_auto_20210108_1720"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="pub_date",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, verbose_name="Date"
            ),
        ),
    ]
