# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-27 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0004_remove_view_blog_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='icon',
            field=models.ImageField(blank=True, upload_to='planet/icons', verbose_name='Icon'),
        ),
    ]
