# Generated by Django 5.2.9 on 2026-01-16 22:18

from django.db import migrations, models

import inyoka.utils.clamav


class Migration(migrations.Migration):
    dependencies = [
        ('planet', '0007_alter_blog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='icon',
            field=models.ImageField(
                blank=True,
                upload_to='planet/icons',
                validators=[inyoka.utils.clamav.validate_file_infection],
                verbose_name='Icon',
            ),
        ),
    ]
