#-*- coding: utf-8 -*-
from inyoka.utils.tests.test_cache import *
from inyoka.utils.tests.test_database import *
from inyoka.utils.tests.test_magic import *
from inyoka.utils.tests.test_slug import *
from inyoka.utils.tests.test_text import *
from inyoka.utils.tests.test_css import *
from inyoka.utils.tests.test_gravatar import *
from inyoka.utils.tests.test_storage import *
from inyoka.utils.tests.test_user import *
from inyoka.utils.tests.test_files import *
