# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-03 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_linkmap'),
        ('portal', '0028_auto_20191117_1807'),
    ]

    operations = [
    ]
