# Generated by Django 1.11.29 on 2020-11-07 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_merge_20200503_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmap',
            name='icon',
            field=models.ImageField(blank=True, upload_to='linkmap/icons', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='linkmap',
            name='token',
            field=models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator(message='Only lowercase letters, - and _ allowed. Numbers as postfix.', regex='^[a-z\\-_]+[1-9]*$')], verbose_name='Token'),
        ),
    ]
