# Generated by Django 2.2.19 on 2021-03-01 00:01
import os

from django.conf import settings
from django.db import migrations


def create_teamicons_folder(apps, schema_editor):
    """Create a folder for the FilePathField User.icon, if it does not exist yet"""

    path = os.path.join(settings.MEDIA_ROOT, 'portal/team_icons')
    os.makedirs(path, exist_ok=True)


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_auto_20201107_2140'),
    ]

    operations = [
        migrations.RunPython(create_teamicons_folder),
    ]
