# Generated by Django 2.2.28 on 2023-03-12 17:04

from django.db import migrations

import inyoka.utils.database


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0032_auto_20210822_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=inyoka.utils.database.InyokaMarkupField(application='ikhaya', blank=True, force_existing=False, simplify=False),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='text',
            field=inyoka.utils.database.InyokaMarkupField(application='portal', force_existing=False, simplify=False, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=inyoka.utils.database.InyokaMarkupField(application='portal', force_existing=False, help_text='Inyoka syntax required.', simplify=False, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='value',
            field=inyoka.utils.database.InyokaMarkupField(application='portal', force_existing=False, simplify=False),
        ),
    ]
