# Generated by Django 3.2.23 on 2023-11-27 00:08

from django.db import migrations

import inyoka.utils.database


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0033_auto_20230312_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jabber',
            field=inyoka.utils.database.JabberField(blank=True, max_length=200, verbose_name='Jabber'),
        ),
    ]
