# Generated by Django 3.2.23 on 2024-02-05 21:55

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0035_auto_20231127_0114'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(django.db.models.functions.text.Upper('username'), name='upper_username_idx'),
        ),
    ]
