# Generated by Django 4.2.20 on 2025-03-22

from django.db import migrations


def remove_sidebar_settings(apps, schema_editor):
    user_model = apps.get_model("portal", "User")

    for user in user_model.objects.filter(settings__contains='sidebar_hidden'):
        for c in ('ikhaya', 'planet', 'admin', 'portal'):
            component = '_'.join([c, 'sidebar_hidden'])
            user.settings.pop(component, None)
        user.save(update_fields=['settings'])


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0041_adjust_datetimes"),
    ]

    operations = [
        migrations.RunPython(
            code=remove_sidebar_settings,
        ),
    ]
