# Generated by Django 5.2.9 on 2026-01-16 22:18

from django.db import migrations, models

import inyoka.portal.user
import inyoka.utils.clamav


class Migration(migrations.Migration):
    dependencies = [
        ('portal', '0042_remove_sidebar_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmap',
            name='icon',
            field=models.ImageField(
                blank=True,
                upload_to='linkmap/icons',
                validators=[inyoka.utils.clamav.validate_file_infection],
                verbose_name='Icon',
            ),
        ),
        migrations.AlterField(
            model_name='staticfile',
            name='file',
            field=models.FileField(
                upload_to='portal/files',
                validators=[inyoka.utils.clamav.validate_file_infection],
                verbose_name='File',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=inyoka.portal.user.upload_to_avatar,
                validators=[inyoka.utils.clamav.validate_file_infection],
                verbose_name='Avatar',
            ),
        ),
    ]
