# Generated by Django 5.2.14 on 2026-05-06 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone

import inyoka.utils.database


def add_default_ticket_reasons(apps, schema_editor):
    TicketReason = apps.get_model('portal', 'TicketReason')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Post = apps.get_model('forum', 'Post')
    Topic = apps.get_model('forum', 'Topic')
    post_ct = ContentType.objects.get_for_model(Post)
    topic_ct = ContentType.objects.get_for_model(Topic)
    TicketReason.objects.create(
        content_type=post_ct, reason='Spam', slug='spam', system_defined=True)
    TicketReason.objects.create(
        content_type=post_ct, reason='Other', system_defined=True)
    TicketReason.objects.create(
        content_type=topic_ct, reason='Other', system_defined=True)


def migrate_old_reported_topics(apps, schema_editor):
    Topic = apps.get_model('forum', 'Topic')
    Ticket = apps.get_model('portal', 'Ticket')
    TicketReason = apps.get_model('portal', 'TicketReason')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Post = apps.get_model('forum', 'Post')
    post_ct = ContentType.objects.get_for_model(Post)
    spam_reason = TicketReason.objects.filter(
        content_type=post_ct, slug='spam').first()
    system_user = apps.get_model(settings.AUTH_USER_MODEL.split('.')[0],
                                 settings.AUTH_USER_MODEL.split('.')[1]
                                 ).objects.filter(username='ubuntuusers').first()

    for topic in Topic.objects.filter(reporter__isnull=False).select_related('reporter', 'report_claimed_by'):
        first_post = Post.objects.filter(topic=topic).order_by('pub_date').first()
        if first_post is None:
            continue
        Ticket.objects.create(
            content_type=post_ct,
            object_id=first_post.id,
            reporting_user=topic.reporter or system_user,
            reporting_time=timezone.now(),
            owning_user=topic.report_claimed_by,
            state=1 if topic.report_claimed_by else 0,
            reason=spam_reason,
            reporter_comment=topic.reported or '',
        )


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("forum", "0020_add_manage_tickets_permission"),
        ("portal", "0043_alter_linkmap_icon_alter_staticfile_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketReason",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("system_defined", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Reason",
                "verbose_name_plural": "Ticket Reasons",
            },
        ),
        migrations.AddConstraint(
            model_name="ticketreason",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slug__isnull", False)),
                fields=("content_type", "slug"),
                name="unique_ticketreason_slug_per_content_type",
            ),
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(db_index=True, null=True)),
                ("reporting_time", models.DateTimeField(db_index=True)),
                ("owned_time", models.DateTimeField(blank=True, null=True)),
                ("closed_time", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.SmallIntegerField(
                        choices=[(0, "Open"), (1, "In Progress"), (2, "Closed")],
                        db_index=True,
                        default=0,
                    ),
                ),
                (
                    "reporter_comment",
                    inyoka.utils.database.InyokaMarkupField(
                        application="portal",
                        blank=True,
                        force_existing=False,
                        simplify=False,
                        verbose_name="Reporter comment",
                    ),
                ),
                (
                    "owner_comment",
                    inyoka.utils.database.InyokaMarkupField(
                        application="portal",
                        blank=True,
                        force_existing=False,
                        null=True,
                        simplify=False,
                        verbose_name="Owner comment",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "owning_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporting_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reported_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portal.ticketreason",
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            code=add_default_ticket_reasons,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=migrate_old_reported_topics,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
