# Generated by Django 5.2.16 on 2026-08-28 22:15

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0043_alter_linkmap_icon_alter_staticfile_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpamEmailAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        unique=True,
                        verbose_name="Email address",
                    ),
                ),
                (
                    "inserted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Inserted at"),
                ),
            ],
            options={
                "verbose_name": "Spam email address",
                "verbose_name_plural": "Spam email addresses",
                "indexes": [
                    models.Index(
                        django.db.models.functions.text.Upper("email"),
                        name="upper_email_idx",
                    )
                ],
            },
        ),
    ]
