# Generated by Django 5.2.17 on 2026-09-13 22:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0044_add_ticket_and_ticketreason"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketreason",
            name="subscribers",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="ticketreason",
            name="system_defined",
            field=models.BooleanField(
                default=False,
                help_text='Used for predefined reasons like "spam" that cannot be edited/deleted from the gui.',
            ),
        ),
    ]
