# Generated by Django 5.2.17 on 2026-09-25 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0046_spamemailaddress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="reason",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portal.ticketreason",
                verbose_name="Reason",
            ),
        ),
    ]
